services:
  mysql:
    image: mysql:8.0
    container_name: cfe_m9mex_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: m9mex_db
      MYSQL_USER: m9mex_user
      MYSQL_PASSWORD: m9mex_pass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
